name: geocoder
description: Forward and reverse geocoding.
version: 0.2.2-nullsafety

flutter:
  plugin:
    platforms:
      android:
        package: com.aloisdeniel.geocoder
        pluginClass: GeocoderPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0-0 <3.0.0"
