name: geocoder
description: Forward and reverse geocoding.
version: 0.2.2
author: Alo√Øs Deniel<alois.deniel@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_geocoder

flutter:
  plugin:
    platforms:
      android:
        package: com.aloisdeniel.geocoder
        pluginClass: GeocoderPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"
